### ISSUE TITLE
SyntaxError: Unexpected token a at Object.parse (native) at DestroyableTransform._transform 

### ISSUE THREAD

**Issue by suppix** [jdumars/lekube#3]
Hello. 
I have some problem with deploying lekube, I have 3 k8s nodes, so I have 3 pods with lekube and all of them have similar problems:
Could you please help me?

kubectl logs lekube-hmnk4 --namespace=lekube
`
undefined:1
nnotation.io.kubernetes.container.terminationMessagePolicy":"File","annotation
                                                                    ^
SyntaxError: Unexpected token a
    at Object.parse (native)
    at DestroyableTransform._transform (/usr/src/app/node_modules/docker-allcontainers/allcontainers.js:27:21)
    at DestroyableTransform.Transform._read (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
`

kubectl logs lekube-rdgn5  --namespace=lekube
`
undefined:1
{"status":"attach","id":"ae2527d33493311d2b40d2768eb29010f922923306f5
                                                                     ^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at DestroyableTransform._transform (/usr/src/app/node_modules/docker-allcontainers/allcontainers.js:27:21)
    at DestroyableTransform.Transform._read (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
`

**Comment by suppix** [comment]
Oh. It looks like it's not the problem with lekube, because with logentries/docker-logentries docker images I get the same error.
